name: beca
description: Highly customizable, feature-packed calendar works like google calendar but with more features.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_icons:
    path: ../packages/flutter-icons-1.1.1/
  animations: ^1.1.2
  badges: ^2.0.1
  beamer: ^1.1.0
  black_hole_flutter: ^0.3.2
  bot_toast: ^3.0.5
  cached_network_image: ^3.0.0
  csv: ^4.0.3
  cupertino_icons: ^1.0.2
  dart_date: null
  dartx: ^0.7.1
  dartz: ^0.10.0-nullsafety.2
  data_connection_checker: ^0.3.4
  date_picker_timeline: ^1.2.3
  extended_image: ^4.1.0
  file_picker: ^3.0.3
  fl_chart: ^0.36.2
  flash: ^1.5.1
  flex_color_picker: ^2.1.1
  flutter_dynamic_icon: ^2.0.0
  flutter_form_builder: ^6.0.1
  flutter_layout_grid: ^1.0.3
  flutter_phoenix: ^1.0.0
  flutter_screenutil: ^4.0.3
  flutter_slidable: ^0.5.7
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  flutter_uix: ^0.1.2-nullsafety.2
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  grouped_list: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.0
  json_diff: ^0.2.0
  liquid_pull_to_refresh: ^3.0.0
  local_auth: ^1.1.6
  logger: ^1.0.0
  marquee: ^2.2.0
  material_design_icons_flutter: ^4.0.5345
  overlay_support: ^1.2.0
  package_info: 2.0.0
  page_transition: ^1.0.9
  path: ^1.6.4
  path_provider: ^2.0.2
  percent_indicator: ^2.1.7+2
  permission_handler: ^8.1.2
  random_string: ^2.0.1
  readmore: ^1.0.1
  rounded_loading_button: ^2.0.5
  shared_preferences: ^2.0.6
  sticky_headers: ^0.1.8
  syncfusion_flutter_calendar: ^19.2.48
  syncfusion_flutter_charts: ^19.2.44+1
  table_calendar: ^3.0.1
  theme_provider: ^0.5.0
  timeago: ^3.1.0
  validators: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.2
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.9
  freezed: ^0.14.2
  hive_generator: ^1.1.0
  json_serializable: ^4.1.3
  mockito: ^5.0.10

dependency_overrides:
  args: ^2.1.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter_native_splash:
  image: assets/images/splash.png
  color: "121212"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/
